# Generated by Django 3.0.3 on 2020-08-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=120)),
                ('tz', models.CharField(max_length=120)),
            ],
        ),
    ]
