# Generated by Django 3.0.3 on 2020-08-01 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20200801_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapi.User', verbose_name='User ID')),
                ('start_time', models.CharField(max_length=120)),
                ('end_time', models.CharField(max_length=120)),
            ],
        ),
    ]
