# Generated by Django 3.0.3 on 2020-08-01 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20200801_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityperiod',
            old_name='user_id',
            new_name='userid',
        ),
    ]
