# Generated by Django 3.0.3 on 2020-08-01 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_auto_20200801_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityperiod',
            old_name='userid',
            new_name='user',
        ),
    ]
